web:
  restart: always
  build: ./web
  expose:
    - "8000"
  command: /usr/local/bin/gunicorn --workers=3 --worker-class=tornado --timeout=90 --graceful-timeout=10 --log-level=DEBUG  -b :8000 app:app
  volumes:
    - /usr/src/app/static

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:web
